WIP 2

diff --git a/provision_service_account b/provision_service_account
--- a/provision_service_account
+++ b/provision_service_account
@@ -2,10 +2,14 @@
 
 set -o errexit
 set -o nounset
+#set -x
 
 GREEN="\033[0;32m"
 YELLOW="\033[0;33m"
 END="\033[0m"
+
+BASH_TRUE=0
+BASH_FALSE=1
 
 script_basename=$(basename "$0")
 
@@ -26,25 +30,31 @@ service_account=""
 
 
 v2_groups=""
+group_exists=""
+group_role_enforced=""
 
 get_dcos_version()
 {
+    echo "INFO: getting DC/OS version"
     dcos_version="$(dcos_get /dcos-metadata/dcos-version.json | jq -r .version)"
     if [[ $? -ne 0 ]]
     then
         echo "Error fetching DC/OS version"
         exit 1
     fi
+    echo "INFO: DC/OS version detected $dcos_version"
 }
 
 get_dcos_security_mode()
 {
+    echo "INFO: getting DC/OS security mode"
     dcos_version="$(dcos_get /dcos-metadata/bootstrap-config.json | jq -r .security)"
     if [[ $? -ne 0 ]]
     then
         echo "Error fetching DC/OS security mode"
         exit 1
     fi
+    echo "INFO: DC/OS security mode detected $dcos_version"
 }
 
 
@@ -56,7 +66,7 @@ dcos_get()
         dcos_url="$(dcos config show core.dcos_url)"
         dcos_auth_token="$(dcos config show core.dcos_acs_token)"
     fi
-    curl -s -k -L -X GET \ 
+    curl -s -k -L -X GET \
         -H "Authorization: token=${dcos_auth_token}" \
         "${dcos_url}/${endpoint}"
 }
@@ -74,22 +84,19 @@ get_v2_groups()
     fi
 }
 
-group_exists()
+get_group_exists()
 {
     local top_level_group="${1}"
+    echo "INFO: cheking if top level group \"$top_level_group\" exists"
     get_v2_groups
-    local group_exists=$(echo "$v2_groups" | jq --arg TLG $top_level_group '[.groups[].id==$TLG] | any')
-    echo "INFO: Group $top_level_group exits is $group_exists"
-    group_exists == "true" ? return $BASH_TRUE : $BASH_FALSE
+    group_exists=$(echo "$v2_groups" | jq --arg TLG $top_level_group '[.groups[].id==$TLG] | any')
 }
 
 get_group_role_enforced()
 {
     local top_level_group="${1}"
     get_v2_groups
-    local group_enforce_role=$(echo "$v2_groups" | jq --arg TLG $top_level_group '.groups[] | select(.id==$TLG) | enforceRole')
-    echo "INFO: Group $top_level_group role enforcement is $group_enforce_role"
-    group_role_enforces == "true" ? return $BASH_TRUE : $BASH_FALSE
+   group_role_enforced=$(echo "$v2_groups" | jq --arg TLG $top_level_group '.groups[] | select(.id==$TLG) | .enforceRole')
 }
 
 # Compute quota_enforced based on service path
@@ -112,7 +119,9 @@ get_quota_enforced_by_path()
     fi
     # else (Non-root level service)_
     top_level_group="${service_name%%/*}"
-    if [[ ! $(group_exists "/${top_level_group}") ]]
+    echo "INFO: Top level group for service \"$service_name\" is $top_level_group"
+    get_group_exists "/${top_level_group}"
+    if [[ "$group_exists" == "false" ]]
     then
         # new group
         echo "INFO: New group setting quota_enforced to TRUE"
@@ -120,7 +129,8 @@ get_quota_enforced_by_path()
     else
         # existing group
         echo "INFO: Existing group need to check enforceRole"
-        if [[ get_group_role_enforced "/${top_level_group}" ]]
+        get_group_role_enforced "/${top_level_group}"
+        if [[ "$group_role_enforced" == "true" ]]
         then
            quota_enforced="true"
         else
@@ -158,18 +168,26 @@ get_service_role()
     local service_name=${1}
 
     # Trim leading and trailing slash
-    service_role="${service_name#/}"
-    service_role="${service_name%/}"
+    service_name="${service_name#/}"
+    service_name="${service_name%/}"
 
-    if [[ -z "$quota_enforced}" ]]
+    if [[ -z "$quota_enforced" ]]
     then
-        get_quota_enforced
+        echo "INFO: Computing quota enforced based on service name $service_name"
+        get_quota_enforced $service_name
+        if [[ -z "$quota_enforced" ]]
+        then
+            echo "Failed to compute quota_enforced"
+            exit 1
+        fi
     fi
-    if [[ "$get_quota_enforced" == "false" ]]
+    if [[ "$quota_enforced" == "false" ]]
     then
-        service_role="${service_role//\//__}-role"
+        echo "INFO: quota enforced FALSE"
+        service_role="${service_name//\//__}-role"
     else
-        service_role="${service_role%%/*}"
+        echo "INFO: quota enforced TRUE"
+        service_role="${service_name%%/*}"
     fi
 }
 
@@ -209,10 +227,12 @@ do
         --package-version) 
             shift
             package_version="${1}"
+            shift
             ;;
         --quota-enforced)
             shift
-            quota_enfoced="${1}"
+            quota_enforced="${1}"
+            shift
             ;;
         -h|--help) 
             usage 
@@ -246,8 +266,8 @@ get_input "Enter service account name" "${service_account}"
 service_account="${answer}"
 
 # Get service role based 
-get_service_role
-if [[ -z "${get_service_role}" ]]
+get_service_role "$service_name"
+if [[ -z "${service_role}" ]]
 then
     echo "Failed to compute service role"
     exit 1
