Initial working commit

diff --git a/provision_service_account b/provision_service_account
--- a/provision_service_account
+++ b/provision_service_account
@@ -8,15 +8,17 @@ GREEN="\033[0;32m"
 YELLOW="\033[0;33m"
 END="\033[0m"
 
-BASH_TRUE=0
-BASH_FALSE=1
-
 script_basename=$(basename "$0")
+script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+package_acls_basedir="${script_dir}/packages"
+verbose="false"
 
 service_name=""
 service_role=""
 service_account=""
 quota_enforced=""
+group_quota_enforced=""
+package_quota_enforced=""
 
 dcos_version=""
 dcos_security_mode=""
@@ -25,36 +27,51 @@ dcos_url=""
 
 package_name=""
 package_version=""
+package_acls_dir=""
+latest_package_version=""
 service_name=""
 service_account=""
-
 
 v2_groups=""
 group_exists=""
 group_role_enforced=""
 
+print_info()
+{
+    if [[ "$verbose" == "true" ]]
+    then
+        echo "INFO: $@"
+    fi
+}
+
+get_latest_package_version()
+{
+    local package_name="${1}"
+    package_version=$(dcos package describe --package-versions "$package_name" | jq -r .[-1])
+}
+
 get_dcos_version()
 {
-    echo "INFO: getting DC/OS version"
+    print_info "getting DC/OS version"
     dcos_version="$(dcos_get /dcos-metadata/dcos-version.json | jq -r .version)"
     if [[ $? -ne 0 ]]
     then
         echo "Error fetching DC/OS version"
         exit 1
     fi
-    echo "INFO: DC/OS version detected $dcos_version"
+    print_info "DC/OS version detected $dcos_version"
 }
 
 get_dcos_security_mode()
 {
-    echo "INFO: getting DC/OS security mode"
-    dcos_version="$(dcos_get /dcos-metadata/bootstrap-config.json | jq -r .security)"
+    print_info "getting DC/OS security mode"
+    dcos_security_mode="$(dcos_get /dcos-metadata/bootstrap-config.json | jq -r .security)"
     if [[ $? -ne 0 ]]
     then
         echo "Error fetching DC/OS security mode"
         exit 1
     fi
-    echo "INFO: DC/OS security mode detected $dcos_version"
+    print_info "DC/OS security mode detected $dcos_version"
 }
 
 
@@ -87,7 +104,7 @@ get_v2_groups()
 get_group_exists()
 {
     local top_level_group="${1}"
-    echo "INFO: cheking if top level group \"$top_level_group\" exists"
+    print_info "cheking if top level group \"$top_level_group\" exists"
     get_v2_groups
     group_exists=$(echo "$v2_groups" | jq --arg TLG $top_level_group '[.groups[].id==$TLG] | any')
 }
@@ -97,6 +114,44 @@ get_group_role_enforced()
     local top_level_group="${1}"
     get_v2_groups
    group_role_enforced=$(echo "$v2_groups" | jq --arg TLG $top_level_group '.groups[] | select(.id==$TLG) | .enforceRole')
+}
+
+get_package_acls_dir()
+{
+    local package_name="${1}"
+    local package_version="${2}"
+
+    package_acls_dir=${package_acls_basedir}/${package_name}/${package_version}
+
+    if [[ ! -d "${package_acls_dir}" ]]
+    then
+        echo "Cannot find package ACLS directory"
+        package_acls_dir=""
+        return 
+    fi
+}
+
+# Compute_ quota_enforced based on package
+get_quota_enforced_by_package()
+{
+    local package_name="${1}"
+    local package_version="${2}"
+
+    get_package_acls_dir "${package_name}" "${package_version}"
+    if [[ -z "$package_acls_dir" ]]
+    then
+        echo "Cannot determine if the package ${package_name} ${package_version} is quota aware"
+        exit 1
+    fi
+
+   if [[ -f "${package_acls_dir}/quota-aware" ]]
+    then
+        print_info "Package $package_name version $package_version is quota aware"
+        package_quota_enforced="true"
+    else
+        print_info "Package $package_name version $package_version is not quota aware"
+        package_quota_enforced="false"
+    fi
 }
 
 # Compute quota_enforced based on service path
@@ -113,38 +168,41 @@ get_quota_enforced_by_path()
     if [[ "$service_name" != */* ]]
     then
         # Root level service
-        echo "INFO: Root level service setting quota_enforced to FALSE"
-        quota_enforced="false"
+        print_info "Root level service setting quota_enforced to FALSE"
+        group_quota_enforced="false"
         return
     fi
     # else (Non-root level service)_
     top_level_group="${service_name%%/*}"
-    echo "INFO: Top level group for service \"$service_name\" is $top_level_group"
+    print_info "Top level group for service \"$service_name\" is $top_level_group"
     get_group_exists "/${top_level_group}"
     if [[ "$group_exists" == "false" ]]
     then
         # new group
-        echo "INFO: New group setting quota_enforced to TRUE"
-        quota_enforced="true"
+        print_info "New group setting quota_enforced to TRUE"
+        group_quota_enforced="true"
     else
         # existing group
-        echo "INFO: Existing group need to check enforceRole"
+        print_info "Existing group need to check enforceRole"
         get_group_role_enforced "/${top_level_group}"
         if [[ "$group_role_enforced" == "true" ]]
         then
-           quota_enforced="true"
+           group_quota_enforced="true"
         else
-           quota_enforced="false"
+           group_quota_enforced="false"
         fi
     fi
 }
 
 # Compute quota enforced based on 
 # 1) DC/OS version
-# 2) Top level group roleEnforce setting
+# 2) Package name and version (if quota aware)
+# 3) Top level group roleEnforce setting
 get_quota_enforced()
 {
     local service_name=${1}
+    local package_name=${2}
+    local package_version=${3}
     get_dcos_version
 
     case $dcos_version in
@@ -153,12 +211,24 @@ get_quota_enforced()
             exit 0
             ;;
         1.*)
-            echo "INFO: DC/OS version 1.x, setting quota_enforced to FALSE"
+            print_info "DC/OS version 1.x, setting quota_enforced to FALSE"
             quota_enforced="false"
             ;;
         2.*)
-            echo "INFO: DC/OS version 2.x, need to analyze further"
-            get_quota_enforced_by_path "${service_name}"
+            print_info "DC/OS version 2.x, need to analyze further"
+            get_quota_enforced_by_package "${package_name}" "${package_version}"
+            if [[ "$package_quota_enforced" == "true" ]]
+            then
+                get_quota_enforced_by_path "${service_name}"
+                if [[ "${group_quota_enforced}" == "true" ]]
+                then
+                   quota_enforced="true"
+               else
+                   quota_enforced="false"
+                fi
+            else
+                quota_enforced="false"
+            fi
             ;;
     esac
 }
@@ -166,6 +236,8 @@ get_quota_enforced()
 get_service_role()
 {
     local service_name=${1}
+    local package_name=${2}
+    local package_version=${3}
 
     # Trim leading and trailing slash
     service_name="${service_name#/}"
@@ -173,8 +245,8 @@ get_service_role()
 
     if [[ -z "$quota_enforced" ]]
     then
-        echo "INFO: Computing quota enforced based on service name $service_name"
-        get_quota_enforced $service_name
+        print_info "Computing quota enforced based on service name $service_name"
+        get_quota_enforced "$service_name" "$package_name" "$package_version" 
         if [[ -z "$quota_enforced" ]]
         then
             echo "Failed to compute quota_enforced"
@@ -183,10 +255,10 @@ get_service_role()
     fi
     if [[ "$quota_enforced" == "false" ]]
     then
-        echo "INFO: quota enforced FALSE"
+        print_info "quota enforced FALSE"
         service_role="${service_name//\//__}-role"
     else
-        echo "INFO: quota enforced TRUE"
+        print_info "quota enforced TRUE"
         service_role="${service_name%%/*}"
     fi
 }
@@ -202,7 +274,7 @@ get_input()
 
 usage()
 {
-    echo "USAGE: provision_service_account <package_name> [--package-version=<version>] [--quota-enforced=false|true]"  
+    echo "USAGE: provision_service_account <package_name> [--package-version=<version>] [--service-name=<service-name>] [--quota-enforced=false|true] [--verbose]"  
 }
 
 grant_user_permission()
@@ -210,14 +282,12 @@ grant_user_permission()
     user=${1}
     perm_string=${2}
     perm_action=${3}
-    description=${4}
 
-    echo "${description}"
-
-    dcos security org users grant ${user} ${perm_string} ${perm_action} --description "${description}"
+    dcos security org users grant ${user} ${perm_string} ${perm_action}
 }
+
 #parse arguments
-ARGS=$(getopt -o h --long "package-version:,quota-enforced:,help" -n "$script_basename" -- "$@")
+ARGS=$(getopt -o hv --long "package-version:,quota-enforced:,service-name:,verbose,help" -n "$script_basename" -- "$@")
 
 eval set -- "$ARGS"
 
@@ -234,9 +304,18 @@ do
             quota_enforced="${1}"
             shift
             ;;
+        --service-name)
+            shift
+            service_name="${1}"
+            shift
+            ;;
         -h|--help) 
             usage 
             exit
+            ;;
+        -v|--verbose) 
+            shift
+            verbose="true"
             ;;
         --)
             shift
@@ -254,32 +333,41 @@ else
     package_name="${1}"
 fi
 
+if [[ -z "$package_version" ]]
+then
+    get_latest_package_version "${package_name}"
+    print_info "Package version not specified, using the latest version ${package_version}"
+fi
+
 command -v dcos >/dev/null 2>&1 || { echo >&2 "Make sure DC/OS CLI is installed.  Aborting."; exit 1; }
 command -v jq >/dev/null 2>&1 || { echo >&2 "Make sure jq is installed.  Aborting."; exit 1; }
 
-get_input "Enter service name" "${package_name}"
-service_name="${answer}"
+if [[ -z "$service_name" ]]
+then
+    get_input "Enter service name" "${package_name}"
+    service_name="${answer}"
+fi
 
-service_account="${service_name#/}"
-service_account="${service_account//\//__}"
-get_input "Enter service account name" "${service_account}"
-service_account="${answer}"
+# Check if CLI is authed with the cluster
+if ! dcos node >/dev/null 2>&1 ; then
+    dcos auth login
+fi
 
 # Get service role based 
-get_service_role "$service_name"
+get_service_role "$service_name" "$package_name" "$package_version"
 if [[ -z "${service_role}" ]]
 then
     echo "Failed to compute service role"
     exit 1
 fi
 
+service_account="${service_name#/}"
+service_account="${service_account//\//__}"
+get_input "Enter service account name" "${service_account}"
+service_account="${answer}"
+
 get_input "Enter secret path" "${service_account}/serviceCredential"
 secret_path="${answer}"
-
-# Check if CLI is authed with the cluster
-if ! dcos node >/dev/null 2>&1 ; then
-    dcos auth login
-fi
 
 if ! dcos security --help > /dev/null 2>&1 ; then
     echo "Installing enterprise(security) CLI subcommand"
@@ -304,55 +392,39 @@ fi
 
 echo "Creating secret"
 #dcos security secrets delete "${secret_path}" &> /dev/null
-if ! dcos security secrets create-sa-secret ${security} private-key.pem "${service_account}" "${secret_path}"; then
+if ! dcos security secrets create-sa-secret private-key.pem "${service_account}" "${secret_path}"; then
     echo "Failed to create secret '${secret_path}' for service account '${service_account}'" >&2
     exit 1
 fi
 
 echo Service account created for account=${service_account} secret=${secret_path}
 
-if [[ "${security}" == "--strict" ]]; then
-    grant_user_permission ${service_account} \
-        "dcos:mesos:master:task:user:nobody" \
-        create \
-        "Allow ${service_account} to execute Mesos tasks as user=nobody"
+get_package_acls_dir "${package_name}" "${package_version}"
+if [[ -z "$package_acls_dir" ]]
+then
+    echo "Cannot determine if the package ${package_name} ${package_version} is quota aware"
+    exit 1
 fi
 
-grant_user_permission ${service_account} \
-    "dcos:mesos:master:framework:role:${service_role}" \
-    create \
-    "Allow ${service_account} to register as a Mesos framework with role=${service_role}"
+get_dcos_security_mode
+if [[ "$dcos_security_mode" == "strict" ]]
+then
+    export strict=true
+fi
+export service_name
+export service_role
+export service_account
 
-grant_user_permission ${service_account} \
-    "dcos:mesos:master:reservation:role:${service_role}" \
-    create \
-    "Allow ${service_account} to create resource reservations on Mesos with role=${service_role}"
-
-grant_user_permission ${service_account} \
-    "dcos:mesos:master:volume:role:${service_role}" \
-    create \
-    "Allow ${service_account} to create volumes on Mesos with role=${service_role}"
-
-grant_user_permission ${service_account} \
-    "dcos:mesos:master:reservation:principal:${service_account}" \
-    delete \
-    "Allow ${service_account} to delete resource reservations on Mesos with principal=${service_account}"
-
-grant_user_permission ${service_account} \
-    "dcos:mesos:master:volume:principal:${service_account}" \
-    delete \
-    "Allow ${service_account} to delete volumes on Mesos with principal=${service_account}"
-
-
-tee "${service_account}-options.json" <<EOF
-{
-  "service": {
-    "name": "${service_name}",
-    "service_account": "${service_account}",
-    "service_account_secret": "${secret_path}"
-  }
-}
-EOF
+package_acls=$(mustache ENV "${package_acls_dir}/acls")
+if [[ $? -ne 0 ]]
+then
+    echo "error computing package ACLs"
+    exit 1
+fi
+while read perm_string perm_action 
+do
+    grant_user_permission "$service_account" "$perm_string" "$perm_action"
+done <<< "$package_acls"
 
 echo "Install the package using :"
 echo "    dcos package install ${package_name} --options=${service_account}-options.json"
